---
# configure_kerberos_kdcs/tasks/configure_replication_on_first_kdc.yml

#
# Add all missing host principals to the krb5.keytab
#

- name: "Export key for secondary KDC host principal's to krb5.keytab on the first KDC"
  command:
    cmd: "kadmin.local ktadd -norandkey -k {{ path_to_krb5_keytab }} host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ secondary_kdcs }}"
  when:
    - 'secondary_kdcs is defined'
    - 'item not in list_of_principals_in_keytab.stdout'
  tags:
    - 'replication_1st_kdc'

#
# systemd timer for replication
#

- name: 'Create a krb5-replication-kprop systemd service for each secondary KDC'
  template:
    src: 'etc_systemd_system_krb5-replication-kprop.service.j2'
    dest: "/etc/systemd/system/krb5-replication-kprop-{{ secondary_kdc_to_sync }}.service"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ secondary_kdcs }}"
  loop_control:
    loop_var: secondary_kdc_to_sync
  when: 'secondary_kdcs is defined'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Restart the krb5-replication-kprop timers'
  tags:
    - 'replication_1st_kdc'

- name: 'Create a systemd timer for each krb5-replication-kprop service'
  template:
    src: 'etc_systemd_system_krb5-replication-kprop.timer.j2'
    dest: "/etc/systemd/system/krb5-replication-kprop-{{ secondary_kdc_to_sync }}.timer"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ secondary_kdcs }}"
  loop_control:
    loop_var: secondary_kdc_to_sync
  when: 'secondary_kdcs is defined'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Restart the krb5-replication-kprop timers'
  tags:
    - 'replication_1st_kdc'

- name: 'Enable the krb5-replication-kprop timers'
  service:
    name: "krb5-replication-kprop-{{ secondary_kdc_to_sync }}.timer"
    enabled: 'true'
  with_items: "{{ secondary_kdcs }}"
  loop_control:
    loop_var: secondary_kdc_to_sync
  when: 'secondary_kdcs is defined'
  tags:
    - 'replication_1st_kdc'
