---
# configure_kerberos_kdcs/tasks/configure_replication_on_first_kdc.yml

#
# list all existing principals
#
- name: 'List all kerberos principals'
  shell:
    cmd: 'kadmin.local listprincs | grep ^host'
  changed_when: 'false'
  check_mode: 'false'
  register: list_of_host_principals
  tags:
    - 'replication_1st_kdc'

#
# create host principal for the first KDC
#
- name: 'Create host principal for the first KDC'
  command:
    cmd: "kadmin.local addprinc -clearpolicy -randkey host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ inventory_hostname }}"
  when: "item not in list_of_host_principals.stdout"
  tags:
    - 'replication_1st_kdc'

#
# create principals for all secondary KDCs
#
- name: 'Create host principals for all secondary KDCs'
  command:
    cmd: "kadmin.local addprinc -clearpolicy -randkey host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ secondary_kdcs }}"
  when:
    - 'secondary_kdcs is defined'
    - 'item not in list_of_host_principals.stdout'
  tags:
    - 'replication_1st_kdc'

#
# Create krb5.keytab if it does not yet exist
#
- name: 'Create krb5.keytab if it does not yet exist'
  command:
    cmd: "kadmin.local ktadd -k {{ path_to_krb5_keytab }} host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
    creates: "{{ path_to_krb5_keytab }}"
  with_items:
    - "{{ inventory_hostname }}"
  tags:
    - 'replication_1st_kdc'

#
# Add all missing host principals to the krb5.keytab
#
- name: 'List principals in they krb5.keytab'
  command:
    cmd: "klist -k -t {{ path_to_krb5_keytab }}"
  changed_when: 'false'
  check_mode: 'false'
  register: list_of_principals_in_keytab
  tags:
    - 'replication_1st_kdc'

- name: "Export key for the first KDC's host principal to to krb5.keytab"
  command:
    cmd: "kadmin.local ktadd -k {{ path_to_krb5_keytab }} host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ inventory_hostname }}"
  when: 'item not in list_of_principals_in_keytab.stdout'
  tags:
    - 'replication_1st_kdc'

- name: "Export key for secondary KDC host principal's to krb5.keytab on the first KDC"
  command:
    cmd: "kadmin.local ktadd -k {{ path_to_krb5_keytab }} host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ secondary_kdcs }}"
  when:
    - 'secondary_kdcs is defined'
    - 'item not in list_of_principals_in_keytab.stdout'
  tags:
    - 'replication_1st_kdc'

#
# systemd timer for replication
#

- name: 'Create systemd service for krb5-replication-kprop'
  template:
    src: 'etc_systemd_system_krb5-replication-kprop.service.j2'
    dest: '/etc/systemd/system/krb5-replication-kprop.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ secondary_kdcs }}"
  loop_control:
    loop_var: secondary_kdc_to_sync
  when: 'secondary_kdcs is defined'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Enable and start the krb5-replication-kprop.timer'
    - 'Restart krb5-replication-kprop.timer'
  tags:
    - 'replication_1st_kdc'

- name: 'Create systemd timer for krb5-replication-kprop'
  template:
    src: 'etc_systemd_system_krb5-replication-kprop.timer.j2'
    dest: '/etc/systemd/system/krb5-replication-kprop.timer'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ secondary_kdcs }}"
  loop_control:
    loop_var: secondary_kdc_to_sync
  when: 'secondary_kdcs is defined'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Enable and start the krb5-replication-kprop.timer'
    - 'Restart krb5-replication-kprop.timer'
  tags:
    - 'replication_1st_kdc'

- name: 'Enable and start the krb5-replication-kprop.timer'
  service:
    name: 'krb5-replication-kprop.timer'
    state: 'started'
    enabled: 'true'
  when: 'secondary_kdcs is defined'
  tags:
    - 'replication_1st_kdc'
