---
# configure_kerberos_kdcs/tasks/create_host_principals.yml

#
# list all existing principals
#
- name: 'List all kerberos principals'
  shell:
    cmd: 'kadmin.local listprincs | grep ^host'
  changed_when: 'false'
  check_mode: 'false'
  register: list_of_host_principals
  tags:
    - 'create_host_principals'
    - 'replication_1st_kdc'

#
# create host principal for the first KDC
#
- name: 'Create host principal for the first KDC'
  command:
    cmd: "kadmin.local addprinc -clearpolicy -randkey host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ inventory_hostname }}"
  when: "item not in list_of_host_principals.stdout"
  tags:
    - 'create_host_principals'
    - 'replication_1st_kdc'

#
# create principals for all desired host principals
#
- name: 'Create host principals for all desired host principals'
  command:
    cmd: "kadmin.local addprinc -clearpolicy -randkey host/{{ item }}.{{ kerberos_dns_domain | default(kerberos_realm | lower) }}"
  with_items:
    - "{{ host_principals_to_create }}"
  when:
    - 'host_principals_to_create is defined'
    - 'item not in list_of_host_principals.stdout'
  tags:
    - 'create_host_principals'
    - 'replication_1st_kdc'
