---
# configure_kerberos_kdcs/tasks/install_packages.yml

- name: 'Install Kerberos KDC packages'
  package:
    name: "{{ kerberos_kdc_packages }}"
    state: 'present'
  notify:
    - 'Remove file kdc.conf (if it was created during installation)'
    - 'Remove file krb5.conf (if it was created during installation)'
    - 'Stop the Kerberos KDC service'
  tags:
    - 'installation'

- name: 'Force all notified handlers to run at this point, not waiting for normal sync points'
  meta: flush_handlers
  tags:
    - 'installation'
