---
# configure_kerberos_kdcs/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'
    - 'replication_1st_kdc'
    - 'replication_other_kdcs'

- name: 'Install packages'
  include_tasks: install_packages.yml
  tags:
    - 'installation'

- name: 'Configure and start the kdc service'
  include_tasks: configure_and_start_the_kdc_service.yml
  tags:
    - 'configuration'

- name: 'Configure the replication on the secondary KDCs'
  include_tasks: configure_replication_on_secondary_kdcs.yml
  when: 'not kdc_is_first_kdc | bool'
  tags:
    - 'replication_other_kdcs'
