---
# configure_kerberos_kdcs/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'
    - 'replication_1st_kdc'
    - 'replication_other_kdcs'

- name: 'Install packages'
  include_tasks: install_packages.yml
  when: 'install_kerberos_packages | bool'
  tags:
    - 'installation'

- name: 'Configure and start the kdc service'
  include_tasks: configure_and_start_the_kdc_service.yml
  when: 'configure_kdc_service | bool'
  tags:
    - 'configuration'

- name: 'Configure and start the kadmin service'
  include_tasks: configure_and_start_the_kadmin_service.yml
  when: 'configure_kadmin_service | bool'
  tags:
    - 'configuration'

- name: 'Create host principals'
  include_tasks: create_host_principals.yml
  when: 'configure_replication_on_first_kdc | bool or create_host_principals | bool'
  tags:
    - 'configuration'
    - 'create_host_principals'
    - 'replication_1st_kdc'

- name: 'Create additional principals (for nfs etc.)'
  include_tasks: create_additional_principals.yml
  when: 'create_host_principals | bool and additional_principals_to_create is defined'
  tags:
    - 'configuration'
    - 'create_host_principals'
    - 'replication_1st_kdc'

- name: 'Create krb5.keytab on the first KDC'
  include_tasks: create_krb5_keytab_on_first_KDC.yml
  when: 'configure_replication_on_first_kdc | bool'
  tags:
    - 'configuration'
    - 'create_host_principals'
    - 'replication_1st_kdc'

- name: 'Configure the replication on the first KDC'
  include_tasks: configure_replication_on_first_kdc.yml
  when: 'configure_replication_on_first_kdc | bool'
  tags:
    - 'replication_1st_kdc'

- name: 'Create and distribute keytabs for other hosts'
  include_tasks: create_and_distribute_keytabs.yml
  when: 'configure_replication_on_first_kdc | bool or create_host_principals | bool'
  tags:
    - 'create_host_principals'
    - 'replication_other_kdcs'

- name: 'Configure the replication on the secondary KDCs'
  include_tasks: configure_replication_on_secondary_kdcs.yml
  when: 'configure_replication_on_secondary_kdcs | bool'
  tags:
    - 'replication_other_kdcs'
