---
# configure_kerberos_kdcs/handlers/main.yml

- name: 'Remove file kdc.conf (if it was created during installation)'
  file:
    path: "{{ path_to_kdc_conf }}"
    state: 'absent'
  tags:
    - 'installation'

- name: 'Remove file krb5.conf (if it was created during installation)'
  file:
    path: "{{ path_to_krb5_conf }}"
    state: 'absent'
  tags:
    - 'installation'

- name: 'Stop the Kerberos KDC service'
  service:
    name: "{{ kerberos_kdc_service }}"
    state: 'stopped'
    masked: 'false'
  tags:
    - 'installation'

- name: 'Restart the Kerberos KDC service'
  service:
    name: "{{ kerberos_kdc_service }}"
    state: 'restarted'
  when: 'kdc_is_first_kdc | bool'
  tags:
    - 'configuration'
