---
# configure_kerberos_kdcs/handlers/main.yml

- name: 'Remove file kdc.conf (if it was created during installation)'
  file:
    path: "{{ path_to_kdc_conf }}"
    state: 'absent'

- name: 'Stop the Kerberos KDC service'
  service:
    name: "{{ kerberos_kdc_service }}"
    state: 'stopped'
    masked: 'false'

- name: 'Restart the Kerberos KDC service'
  service:
    name: "{{ kerberos_kdc_service }}"
    state: 'restarted'
